# Generated by Django 3.0.7 on 2021-07-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acc_code',
            name='Code',
        ),
        migrations.AddField(
            model_name='acc_code',
            name='relatedToId',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
