# Generated by Django 3.0.7 on 2021-07-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingApp', '0003_auto_20210715_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_code',
            name='Flag',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
