# Generated by Django 3.0.7 on 2021-07-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingApp', '0004_auto_20210715_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc_code',
            name='deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
