# Generated by Django 3.0.7 on 2021-07-22 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountingApp', '0005_acc_code_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='acc_code_With_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.BooleanField(default=False, null=True)),
                ('price', models.CharField(default=None, max_length=500, null=True)),
                ('note', models.CharField(default=None, max_length=500, null=True)),
                ('currency', models.CharField(default=None, max_length=500, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accountingApp.acc_code')),
            ],
            options={
                'db_table': 'acc_code_With_details',
            },
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Doc_Number', models.CharField(default=None, max_length=500, null=True)),
                ('Qyed_Number', models.CharField(default=None, max_length=500, null=True)),
                ('Check_Number', models.CharField(default=None, max_length=500, null=True)),
                ('maqbodat_Total', models.CharField(default=None, max_length=500, null=True)),
                ('madfo3at_Total', models.CharField(default=None, max_length=500, null=True)),
                ('acc_codes_With_details_madfo3at', models.ManyToManyField(related_name='madfo3at_acc_codes', to='accountingApp.acc_code_With_details')),
                ('acc_codes_With_details_maqbodat', models.ManyToManyField(related_name='maqbodat_acc_codes', to='accountingApp.acc_code_With_details')),
                ('madfo3at', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madfo3at', to='accountingApp.acc_code')),
                ('maqbodat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maqbodat', to='accountingApp.acc_code')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
