# Generated by Django 3.0.7 on 2021-07-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingApp', '0006_acc_code_with_details_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Notes',
            field=models.TextField(default=None, null=True),
        ),
    ]
